# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revcomp', '0002_auto_20160705_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Getinput',
        ),
    ]
